import type { ShapeDefinition, ShapeResizePolicy, ShapeToolId, Solid3DFamily } from './types';
import { CONNECTOR_RULE_BY_ID, SHAPE_SEMANTICS } from './semantics';
import { buildShapeParameterMetadata, shapeDataCapabilities } from './parameters';
import { SOLID3D_CANONICAL_CUBE_ROTATION_X_DEGREES, SOLID3D_CANONICAL_CUBE_ROTATION_Y_DEGREES,
  SOLID3D_CANONICAL_CUBE_ROTATION_Z_DEGREES, SOLID3D_CANONICAL_CUBOID_ROLL_DEGREES } from './solid3d';

const solidFamilyByGeometry: Partial<Record<ShapeDefinition['geometry'], Solid3DFamily>> = {
  cube3d: 'box', cuboid3d: 'box', cylinder3d: 'revolved', cone3d: 'revolved', coneFrustum3d: 'revolved',
  sphere3d: 'revolved', pyramid3d: 'pyramid', quadrilateralPyramid3d: 'pyramid',
  rightQuadrilateralPyramid3d: 'pyramid', rightTrapezoidPyramid3d: 'pyramid',
  rightTrapezoidPerpendicularPyramid3d: 'pyramid', pyramidFrustum3d: 'pyramid',
  pentagonalPyramid3d: 'pyramid', hexagonalPyramid3d: 'pyramid', tetrahedron3d: 'polyhedron',
  rightTetrahedron3d: 'polyhedron', octahedron3d: 'polyhedron', triangularPrism3d: 'prism',
  quadrilateralPrism3d: 'prism', squarePrism3d: 'prism', pentagonalPrism3d: 'prism', hexagonalPrism3d: 'prism',
};

const shape = <const T extends ShapeDefinition>(definition: T) => ({
  ...definition,
  // Preserve historical Flowchart semantic IDs for old-board deserialization, but never expose
  // those definitions as new tools, picker cards, search results, or category navigation.
  ...(definition.category === 'Flowchart' ? { pickerVisible: false as const } : {}),
  parameterMetadata: buildShapeParameterMetadata(definition),
  dataCapabilities: shapeDataCapabilities(definition),
  ...(SHAPE_SEMANTICS[definition.id] ? { semantic: SHAPE_SEMANTICS[definition.id] } : {}),
  ...(definition.kind === 'connector' ? {
    connectorRule: definition.connectorRule ?? CONNECTOR_RULE_BY_ID[definition.id] ?? 'generic' as const,
    routeKind: definition.routeKind ?? 'straight' as const,
  } : {}),
  ...(solidFamilyByGeometry[definition.geometry] ? { solid3d: { family: solidFamilyByGeometry[definition.geometry]! } } : {}),
});

const B = 'Basic' as const;
const D = '3D Shapes' as const;
const F = 'Flowchart' as const;
const E = 'ERD / Database' as const;
const UC = 'Use Case Diagram' as const;
const C = 'Class Diagram' as const;
const S = 'Sequence Diagram' as const;
const ACT = 'Activity Diagram' as const;
const ST = 'State Diagram' as const;

/**
 * Canonical, semantic shape library. Definitions deliberately share a small set of native
 * geometries; `id` is the persistent semantic identity and `toolId` is the picker/tool identity.
 */
export const SHAPE_DEFINITIONS = [
  // Basic — legacy tool ids/storage types are retained for persisted boards and integrations.
  shape({ id: 'basic.rectangle', toolId: 'rect', label: 'Rectangle', category: B, kind: 'shape', geometry: 'rect', description: 'Independent-width and height rectangle.', width: 120, height: 80, legacyType: 'rect', preview: 'rect' }),
  shape({ id: 'basic.callout', toolId: 'callout', label: 'Callout', category: B, kind: 'shape', geometry: 'callout', description: 'Speech callout with an editable native pointer tail.', width: 120, height: 92, defaultParams: { tailPosition: 0.24 }, preview: 'callout' }),
  shape({ id: 'basic.rounded-rectangle', toolId: 'rounded-rect', label: 'Rounded Rectangle', category: B, kind: 'shape', geometry: 'roundedRect', description: 'Rounded rectangle with a proportional corner radius; legacy absolute radii remain supported.', width: 120, height: 80, legacyType: 'rounded-rect', defaultParams: { cornerRadiusRatio: 0.175 }, preview: 'roundedRect' }),
  shape({ id: 'basic.square', toolId: 'square', label: 'Square', category: B, kind: 'shape', geometry: 'rect', description: 'Equal-width and height rectangle.', width: 88, height: 88, aspectLocked: true, preview: 'rect' }),
  shape({ id: 'basic.ellipse', toolId: 'ellipse', label: 'Ellipse', category: B, kind: 'shape', geometry: 'ellipse', description: 'Ellipse with independent horizontal and vertical radii.', width: 120, height: 80, legacyType: 'ellipse', preview: 'ellipse' }),
  shape({ id: 'basic.circle', toolId: 'circle', label: 'Circle', category: B, kind: 'shape', geometry: 'ellipse', description: 'Circle with equal radii.', width: 88, height: 88, aspectLocked: true, preview: 'ellipse' }),
  shape({ id: 'basic.triangle', toolId: 'triangle', label: 'Triangle', category: B, kind: 'shape', geometry: 'triangle', description: 'Three-sided polygon with editable vertices.', width: 100, height: 88, legacyType: 'triangle', preview: 'triangle' }),
  shape({ id: 'basic.right-triangle', toolId: 'right-triangle', label: 'Right Triangle', category: B, kind: 'shape', geometry: 'rightTriangle', description: 'Right-angled triangle fitted to its editable bounding box.', width: 120, height: 80, legacyType: 'right-triangle', preview: 'rightTriangle' }),
  shape({ id: 'basic.diamond', toolId: 'diamond', label: 'Diamond / Rhombus', category: B, kind: 'shape', geometry: 'diamond', description: 'Four-point diamond fitted to its bounding box.', width: 100, height: 88, legacyType: 'diamond', preview: 'diamond' }),
  shape({ id: 'basic.parallelogram', toolId: 'parallelogram', label: 'Parallelogram', category: B, kind: 'shape', geometry: 'parallelogram', description: 'Skewed quadrilateral with a persistent skew ratio.', width: 120, height: 80, legacyType: 'parallelogram', defaultParams: { skew: 0.2 }, preview: 'parallelogram' }),
  shape({ id: 'basic.trapezoid', toolId: 'trapezoid', label: 'Trapezoid', category: B, kind: 'shape', geometry: 'trapezoid', description: 'Trapezoid with a persistent top-width ratio.', width: 120, height: 80, legacyType: 'trapezoid', defaultParams: { topRatio: 0.58 }, preview: 'trapezoid' }),
  shape({ id: 'basic.pentagon', toolId: 'pentagon', label: 'Pentagon', category: B, kind: 'shape', geometry: 'regularPolygon', description: 'Regular five-sided polygon.', width: 92, height: 92, legacyType: 'pentagon', defaultParams: { sides: 5 }, preview: 'regularPolygon' }),
  shape({ id: 'basic.hexagon', toolId: 'hexagon', label: 'Hexagon', category: B, kind: 'shape', geometry: 'regularPolygon', description: 'Regular six-sided polygon.', width: 92, height: 92, legacyType: 'hexagon', defaultParams: { sides: 6 }, preview: 'regularPolygon' }),
  shape({ id: 'basic.heptagon', toolId: 'heptagon', label: 'Heptagon', category: B, kind: 'shape', geometry: 'regularPolygon', description: 'Regular seven-sided polygon.', width: 92, height: 92, defaultParams: { sides: 7 }, preview: 'regularPolygon' }),
  shape({ id: 'basic.octagon', toolId: 'octagon', label: 'Octagon', category: B, kind: 'shape', geometry: 'regularPolygon', description: 'Regular eight-sided polygon.', width: 92, height: 92, defaultParams: { sides: 8 }, preview: 'regularPolygon' }),
  shape({ id: 'basic.nonagon', toolId: 'nonagon', label: 'Nonagon', category: B, kind: 'shape', geometry: 'regularPolygon', description: 'Regular nine-sided polygon.', width: 92, height: 92, defaultParams: { sides: 9 }, preview: 'regularPolygon' }),
  shape({ id: 'basic.decagon', toolId: 'decagon', label: 'Decagon', category: B, kind: 'shape', geometry: 'regularPolygon', description: 'Regular ten-sided polygon.', width: 92, height: 92, defaultParams: { sides: 10 }, preview: 'regularPolygon' }),
  shape({ id: 'basic.star', toolId: 'star', label: 'Star', category: B, kind: 'shape', geometry: 'star', description: 'Five-point star with editable point count and inner radius.', width: 92, height: 92, legacyType: 'star', defaultParams: { points: 5, innerRatio: 0.42 }, preview: 'star' }),
  shape({ id: 'basic.cross', toolId: 'cross', label: 'Cross', category: B, kind: 'shape', geometry: 'cross', description: 'Cross with editable arm proportions.', width: 92, height: 92, defaultParams: { armRatio: 0.34 }, preview: 'cross' }),
  shape({ id: 'basic.heart', toolId: 'heart', label: 'Heart', category: B, kind: 'shape', geometry: 'heart', description: 'Cubic Bézier heart silhouette.', width: 100, height: 88, preview: 'heart' }),
  shape({ id: 'basic.cloud', toolId: 'cloud', label: 'Cloud', category: B, kind: 'shape', geometry: 'cloud', description: 'Closed cloud silhouette composed of smooth curves.', width: 120, height: 82, preview: 'cloud' }),
  shape({ id: 'basic.cylinder', toolId: 'cylinder', label: 'Cylinder', category: B, kind: 'shape', geometry: 'cylinder', description: 'Database cylinder with curved caps.', width: 104, height: 96, pickerVisible: false, preview: 'cylinder' }),
  shape({ id: 'basic.document', toolId: 'document', label: 'Document', category: B, kind: 'shape', geometry: 'document', description: 'Legacy Basic-library document retained for saved boards; not a new drawing tool.', width: 104, height: 96, pickerVisible: false, preview: 'document' }),
  // Retained for saved boards that reference the former Basic-library actor; UML owns the sole picker entry.
  shape({ id: 'basic.actor', toolId: 'actor', label: 'Actor', category: UC, kind: 'shape', geometry: 'actor', description: 'Legacy actor identity routed through the shared parametric UML actor geometry.', width: 74, height: 104, resizePolicy: { mode: 'aspect', aspectRatio: 74 / 104 }, pickerVisible: false, preview: 'actor' }),
  shape({ id: 'basic.frame', toolId: 'frame', label: 'Frame', category: B, kind: 'shape', geometry: 'frame', description: 'Legacy Basic frame; diagram frames live in their UML diagram libraries.', width: 140, height: 96, pickerVisible: false, defaultParams: { title: 'Frame' }, preview: 'frame' }),

  // The 3D solids share one fixed affine cabinet-style oblique projection, family-aligned
  // canonical poses, semantic topology, per-solid local dimensions, and persisted XYZ rotation.
  shape({ id: '3d.cuboid', toolId: '3d-cuboid', label: 'Cuboid', category: D, kind: 'shape', geometry: 'cuboid3d', description: 'Rectangular prism with independent local X width, Y depth, and Z height dimensions; projected bounds are derived.', searchAliases: ['Rectangular Prism', 'Rectangular Box', 'Parallelepiped'], width: 116, height: 92, defaultText: '', defaultScale3d: { x: 1.35, y: 0.72, z: 1 }, defaultParams: { rotationX: 0, rotationY: 0, rotationZ: SOLID3D_CANONICAL_CUBOID_ROLL_DEGREES }, preview: 'solid3d' }),
  shape({ id: '3d.cube', toolId: '3d-cube', label: 'Cube', category: D, kind: 'shape', geometry: 'cube3d', description: 'True equal-edge cube in the canonical local pose. Resizing changes one shared 3D edge length, never stretches it into a cuboid.', width: 92, height: 92, resizePolicy: { mode: 'aspect', aspectRatio: 1.1 }, defaultText: '', defaultParams: { rotationX: SOLID3D_CANONICAL_CUBE_ROTATION_X_DEGREES, rotationY: SOLID3D_CANONICAL_CUBE_ROTATION_Y_DEGREES,
    rotationZ: SOLID3D_CANONICAL_CUBE_ROTATION_Z_DEGREES }, preview: 'solid3d' }),
  shape({ id: '3d.cylinder', toolId: '3d-cylinder', label: 'Cylinder', category: D, kind: 'shape', geometry: 'cylinder3d', description: 'Textbook cylinder with circular bases, visible/hidden rim arcs, silhouette generators, and three-axis rotation.', width: 104, height: 94, pickerVisible: false, defaultText: '', defaultParams: { depth: 0.78, rotationX: 0, rotationY: 0, rotationZ: 0 }, preview: 'solid3d' }),
  shape({ id: '3d.cone', toolId: '3d-cone', label: 'Cone', category: D, kind: 'shape', geometry: 'cone3d', description: 'Textbook cone with one circular base, two silhouette generators, and orientation-aware hidden base arcs.', width: 96, height: 92, defaultText: '', defaultParams: { depth: 0.78, rotationX: 0, rotationY: 0, rotationZ: 0 }, preview: 'solid3d' }),
  shape({ id: '3d.sphere', toolId: '3d-sphere', label: 'Sphere', category: D, kind: 'shape', geometry: 'sphere3d', description: 'Isotropic sphere with one equatorial great circle and a dynamically split visible/hidden half.', width: 96, height: 96, resizePolicy: { mode: 'aspect', aspectRatio: 1 }, defaultText: '', defaultParams: { rotationX: 0, rotationY: 0, rotationZ: 0 }, preview: 'solid3d' }),
  shape({ id: '3d.pyramid', toolId: '3d-pyramid', label: 'Pyramid', category: D, kind: 'shape', geometry: 'pyramid3d', description: 'Square-based pyramid with an XY base, local-Z height, editable side count, and meaningful X/Y apex offsets.', searchAliases: ['Square Pyramid', 'Square-Based Pyramid'], width: 108, height: 94, defaultText: '', defaultParams: { sides: 4, depth: 1, apexOffsetX: 0, apexOffsetY: 0, rotationX: 0, rotationY: 0, rotationZ: 0 }, preview: 'solid3d' }),
  shape({ id: '3d.quadrilateral-pyramid', toolId: '3d-quadrilateral-pyramid', label: 'Quadrilateral Pyramid', category: D, kind: 'shape', geometry: 'quadrilateralPyramid3d', description: 'Pyramid over a fixed, visibly irregular convex quadrilateral XY base; its local-Z height and X/Y apex offsets remain independent.', searchAliases: ['Convex Quadrilateral Pyramid'], width: 108, height: 94, defaultText: '', defaultParams: { depth: 1, apexOffsetX: 0.2, apexOffsetY: 0, rotationX: 0, rotationY: 0, rotationZ: 0 }, preview: 'solid3d' }),
  shape({ id: '3d.right-quadrilateral-pyramid', toolId: '3d-right-quadrilateral-pyramid', label: 'Right Quadrilateral Pyramid', category: D, kind: 'shape', geometry: 'rightQuadrilateralPyramid3d', description: 'Right pyramid with a rectangular XY base and a local-Z altitude directly above its base-area centroid; distinct from the generic irregular Quadrilateral Pyramid.', searchAliases: ['Right Rectangular Pyramid', 'Rectangular-Based Right Pyramid'], searchKeywords: ['right pyramid', 'perpendicular altitude', 'rectangle base'], width: 108, height: 94, defaultText: '', defaultParams: { depth: 1, rotationX: 0, rotationY: 0, rotationZ: 0 }, preview: 'solid3d' }),
  shape({ id: '3d.right-trapezoid-pyramid', toolId: '3d-right-trapezoid-pyramid', label: 'Right-Trapezoid-Based Pyramid', category: D, kind: 'shape', geometry: 'rightTrapezoidPyramid3d', description: 'Pyramid over a genuine right-trapezoid XY base (one perpendicular leg and one pair of parallel bases); the local-Z apex altitude stands above the base area centroid.', searchAliases: ['Pyramid with Right-Trapezoid Base', 'Trapezoidal Pyramid with Right Base'], searchKeywords: ['trapezoid pyramid', 'right trapezoid', 'parallel bases', 'perpendicular base leg'], width: 108, height: 94, defaultText: '', defaultParams: { depth: 1, rotationX: 0, rotationY: 0, rotationZ: 0 }, preview: 'solid3d' }),
  shape({ id: '3d.right-trapezoid-perpendicular-pyramid', toolId: '3d-right-trapezoid-perpendicular-pyramid', label: 'Right-Trapezoid-Based Pyramid with One Perpendicular Lateral Edge', category: D, kind: 'shape', geometry: 'rightTrapezoidPerpendicularPyramid3d', description: 'Pyramid over the same right-trapezoid XY base; its apex is directly above base vertex A, so exactly one lateral edge is perpendicular to the base plane.', searchAliases: ['Right-Trapezoid Pyramid with One Perpendicular Lateral Edge', 'Trapezoidal Pyramid with Vertical Lateral Edge'], searchKeywords: ['one perpendicular lateral edge', 'vertical lateral edge', 'pyramid height along Z'], width: 118, height: 100, defaultText: '', defaultParams: { depth: 1, rotationX: 0, rotationY: 0, rotationZ: 0 }, preview: 'solid3d' }),
  shape({ id: '3d.tetrahedron', toolId: '3d-tetrahedron', label: 'Tetrahedron', category: D, kind: 'shape', geometry: 'tetrahedron3d', description: 'Regular four-face tetrahedron with an XY triangular base, local-Z apex, and volume-centroid origin.', searchAliases: ['Triangular Pyramid', 'Regular Triangular Pyramid', 'Regular Tetrahedron'], width: 96, height: 92, defaultText: '', defaultScale3d: { x: 1, y: 1, z: 1 }, defaultParams: { depth: 1, rotationX: 0, rotationY: 0, rotationZ: 0 }, preview: 'solid3d' }),
  shape({ id: '3d.right-tetrahedron', toolId: '3d-right-tetrahedron', label: 'Right Tetrahedron', category: D, kind: 'shape', geometry: 'rightTetrahedron3d', description: 'Trirectangular tetrahedron: three pairwise-perpendicular legs meet at one vertex; the +Z altitude is adjustable.', searchAliases: ['Trirectangular Tetrahedron', 'Right Triangular Pyramid', 'Tetrahedron with Perpendicular Height'], width: 100, height: 94, defaultText: '', defaultParams: { heightRatio: 1, rotationX: 0, rotationY: 0, rotationZ: 0 }, preview: 'solid3d' }),
  shape({ id: '3d.octahedron', toolId: '3d-octahedron', label: 'Octahedron', category: D, kind: 'shape', geometry: 'octahedron3d', description: 'Eight triangular faces and twelve edges with rotation-aware visible/hidden classification.', width: 100, height: 94, defaultText: '', defaultParams: { depth: 1, rotationX: 0, rotationY: 0, rotationZ: 0 }, preview: 'solid3d' }),
  shape({ id: '3d.triangular-prism', toolId: '3d-triangular-prism', label: 'Triangular Prism', category: D, kind: 'shape', geometry: 'triangularPrism3d', description: 'Right triangular prism with congruent XY triangular bases, X width, Y base height, and local-Z extrusion.', width: 116, height: 90, defaultText: '', defaultParams: { sides: 3, depth: 0.82, rotationX: 0, rotationY: 0, rotationZ: 0 }, preview: 'solid3d' }),
  shape({ id: '3d.quadrilateral-prism', toolId: '3d-quadrilateral-prism', label: 'Quadrilateral Prism', category: D, kind: 'shape', geometry: 'quadrilateralPrism3d', description: 'Right prism with a fixed, visibly irregular convex quadrilateral XY base and matching bases separated along local Z.', searchAliases: ['Convex Quadrilateral Prism'], width: 116, height: 94, defaultText: '', defaultParams: { depth: 0.82, rotationX: 0, rotationY: 0, rotationZ: 0 }, preview: 'solid3d' }),
  shape({ id: '3d.pentagonal-prism', toolId: '3d-pentagonal-prism', label: 'Pentagonal Prism', category: D, kind: 'shape', geometry: 'pentagonalPrism3d', description: 'Right prism with congruent pentagonal XY bases and local-Z extrusion.', width: 112, height: 94, defaultText: '', defaultParams: { sides: 5, depth: 0.8, rotationX: 0, rotationY: 0, rotationZ: 0 }, preview: 'solid3d' }),
  shape({ id: '3d.hexagonal-prism', toolId: '3d-hexagonal-prism', label: 'Hexagonal Prism', category: D, kind: 'shape', geometry: 'hexagonalPrism3d', description: 'Right prism with congruent hexagonal XY bases and depth-aware hidden edges along local Z.', width: 110, height: 92, defaultText: '', defaultParams: { sides: 6, depth: 0.78, rotationX: 0, rotationY: 0, rotationZ: 0 }, preview: 'solid3d' }),
  shape({ id: '3d.square-prism', toolId: '3d-square-prism', label: 'Square Prism', category: D, kind: 'shape', geometry: 'squarePrism3d', description: 'Right prism with a square XY base; distinct from the equal-edge cube preset by its local-Z length.', width: 112, height: 94, pickerVisible: false, defaultText: '', defaultParams: { sides: 4, depth: 1.35, rotationX: 0, rotationY: 0, rotationZ: 0 }, preview: 'solid3d' }),
  shape({ id: '3d.pentagonal-pyramid', toolId: '3d-pentagonal-pyramid', label: 'Pentagonal Pyramid', category: D, kind: 'shape', geometry: 'pentagonalPyramid3d', description: 'Pentagonal XY-based pyramid with independently editable local-Z height, X/Y apex offsets, and orientation.', width: 108, height: 94, defaultText: '', defaultParams: { sides: 5, depth: 1, apexOffsetX: 0, apexOffsetY: 0, rotationX: 0, rotationY: 0, rotationZ: 0 }, preview: 'solid3d' }),
  shape({ id: '3d.hexagonal-pyramid', toolId: '3d-hexagonal-pyramid', label: 'Hexagonal Pyramid', category: D, kind: 'shape', geometry: 'hexagonalPyramid3d', description: 'Hexagonal XY-based pyramid with independently editable local-Z height, X/Y apex offsets, and orientation.', width: 108, height: 94, defaultText: '', defaultParams: { sides: 6, depth: 1, apexOffsetX: 0, apexOffsetY: 0, rotationX: 0, rotationY: 0, rotationZ: 0 }, preview: 'solid3d' }),
  shape({ id: '3d.pyramid-frustum', toolId: '3d-pyramid-frustum', label: 'Pyramid Frustum', category: D, kind: 'shape', geometry: 'pyramidFrustum3d', description: 'Truncated regular pyramid with editable base side count and top-to-base radius ratio.', searchAliases: ['Truncated Pyramid', 'Frustum of a Pyramid'], width: 108, height: 94, defaultText: '', defaultParams: { sides: 4, topRadiusRatio: 0.38, depth: 1, rotationX: 0, rotationY: 0, rotationZ: 0 }, preview: 'solid3d' }),
  shape({ id: '3d.cone-frustum', toolId: '3d-cone-frustum', label: 'Cone Frustum', category: D, kind: 'shape', geometry: 'coneFrustum3d', description: 'Truncated cone with editable top radius, depth, and three-axis orientation.', searchAliases: ['Truncated Cone', 'Conical Frustum'], width: 108, height: 94, defaultText: '', defaultParams: { topRadiusRatio: 0.38, depth: 0.78, rotationX: 0, rotationY: 0, rotationZ: 0 }, preview: 'solid3d' }),

  // Connectors are a dedicated polyline/curve model, not unions of rectangle and triangle objects.
  shape({ id: 'connector.line', toolId: 'line', label: 'Line', category: B, kind: 'connector', geometry: 'rect', description: 'Editable straight connector with independently draggable endpoints.', searchAliases: ['Straight Connector', 'connector.straight'], width: 120, height: 0, legacyType: 'line', connector: { endMarker: 'none' }, preview: 'line' }),
  shape({ id: 'connector.arrow', toolId: 'arrow', label: 'Arrow', category: B, kind: 'connector', geometry: 'rect', description: 'Straight connector with a filled arrowhead.', width: 120, height: 0, pickerVisible: false, legacyType: 'arrow', connector: { endMarker: 'arrow' }, preview: 'arrow' }),
  shape({ id: 'connector.double-arrow', toolId: 'double-arrow', label: 'Double Arrow', category: B, kind: 'connector', geometry: 'rect', description: 'Straight connector with arrowheads at both ends.', width: 120, height: 0, pickerVisible: false, connector: { startMarker: 'arrow', endMarker: 'arrow' }, preview: 'double-arrow' }),
  shape({ id: 'connector.open-arrow', toolId: 'open-arrow', label: 'Open Arrow', category: B, kind: 'connector', geometry: 'rect', description: 'Straight connector with an open arrowhead.', width: 120, height: 0, pickerVisible: false, connector: { endMarker: 'openArrow' }, preview: 'open-arrow' }),
  shape({ id: 'connector.block-arrow', toolId: 'block-arrow', label: 'Block Arrow', category: B, kind: 'shape', geometry: 'blockArrow', description: 'Block arrow silhouette with an adjustable shaft proportion.', width: 132, height: 68, defaultParams: { shaftRatio: 0.38 }, preview: 'block-arrow' }),
  shape({ id: 'connector.curved-arrow', toolId: 'curved-arrow', label: 'Curved Arrow', category: B, kind: 'connector', geometry: 'rect', description: 'Cubic Bézier connector with a filled arrowhead.', width: 120, height: 80, pickerVisible: false, routeKind: 'curved', connector: { endMarker: 'arrow' }, preview: 'curved-arrow' }),
  // Compatibility alias for the visible Line tool; kept registered for saved tool/shape references.
  shape({ id: 'connector.straight', toolId: 'connector', label: 'Connector', category: B, kind: 'connector', geometry: 'rect', description: 'Straight connector that can snap to shape connection points.', width: 120, height: 0, pickerVisible: false, connector: { endMarker: 'none' }, preview: 'line' }),
  shape({ id: 'connector.orthogonal', toolId: 'orthogonal-connector', label: 'Orthogonal Connector', category: B, kind: 'connector', geometry: 'rect', description: 'Horizontal and vertical routed connector with editable waypoints.', width: 120, height: 80, routeKind: 'orthogonal', connector: { endMarker: 'arrow' }, preview: 'orthogonal' }),
  shape({ id: 'connector.elbow', toolId: 'elbow-connector', label: 'Elbow Connector', category: B, kind: 'connector', geometry: 'rect', description: 'Two-segment horizontal/vertical elbow connector.', width: 120, height: 80, routeKind: 'elbow', connector: { endMarker: 'arrow' }, preview: 'elbow' }),
  shape({ id: 'connector.dashed', toolId: 'dashed-connector', label: 'Dashed Connector', category: B, kind: 'connector', geometry: 'rect', description: 'Dashed connector that snaps to compatible shape ports.', width: 120, height: 0, connector: { lineStyle: 'dashed', endMarker: 'arrow' }, preview: 'dashed' }),
  shape({ id: 'connector.waypoint', toolId: 'waypoint', label: 'Waypoint', category: B, kind: 'shape', geometry: 'waypoint', description: 'Retained for saved connector-routing metadata; not a stand-alone drawing primitive.', width: 16, height: 16, pickerVisible: false, aspectLocked: true, preview: 'waypoint' }),
  shape({ id: 'connector.junction', toolId: 'junction', label: 'Junction / Connection Point', category: B, kind: 'shape', geometry: 'junction', description: 'Retained compatibility target for existing boards; use diagram-specific pseudostates instead.', width: 20, height: 20, pickerVisible: false, aspectLocked: true, preview: 'junction' }),

  // Flowchart: semantic ids remain distinct while related symbols share geometry.
  shape({ id: 'flow.process', toolId: 'flow-process', label: 'Process', category: F, kind: 'shape', geometry: 'rect', description: 'Flowchart process step.', width: 120, height: 72, defaultText: 'Process', preview: 'rect' }),
  shape({ id: 'flow.decision', toolId: 'flow-decision', label: 'Decision', category: F, kind: 'shape', geometry: 'diamond', description: 'Flowchart decision or branch.', width: 112, height: 88, defaultText: 'Decision', preview: 'diamond' }),
  shape({ id: 'flow.terminator', toolId: 'flow-terminator', label: 'Terminator / Start-End', category: F, kind: 'shape', geometry: 'capsule', description: 'Flowchart start or end capsule.', width: 128, height: 58, defaultText: 'Start / End', preview: 'capsule' }),
  shape({ id: 'flow.input-output', toolId: 'flow-input-output', label: 'Input / Output', category: F, kind: 'shape', geometry: 'parallelogram', description: 'Flowchart data input or output.', searchAliases: ['Data Symbol', 'flow.data', 'flow-data', 'Input-Output'], width: 128, height: 70, defaultText: 'Input / Output', defaultParams: { skew: 0.18 }, preview: 'parallelogram' }),
  shape({ id: 'flow.predefined-process', toolId: 'flow-predefined-process', label: 'Predefined Process', category: F, kind: 'shape', geometry: 'predefinedProcess', description: 'Predefined process/subroutine with two vertical boundary rules.', width: 128, height: 72, defaultText: 'Predefined Process', preview: 'predefined-process' }),
  shape({ id: 'flow.document', toolId: 'flow-document', label: 'Document', category: F, kind: 'shape', geometry: 'document', description: 'Flowchart document with a curved lower edge.', searchAliases: ['Flowchart Document', 'basic.document', 'Basic Document'], width: 112, height: 84, legacyType: 'document', defaultText: 'Document', preview: 'document' }),
  shape({ id: 'flow.multiple-documents', toolId: 'flow-multiple-documents', label: 'Multiple Documents', category: F, kind: 'shape', geometry: 'multipleDocuments', description: 'Layered flowchart document stack.', width: 126, height: 92, defaultText: 'Documents', preview: 'multiple-documents' }),
  shape({ id: 'flow.database', toolId: 'flow-database', label: 'Database / Stored Data', category: F, kind: 'shape', geometry: 'cylinder', description: 'Stored data symbol using database-cylinder geometry.', width: 104, height: 88, defaultText: 'Database', preview: 'cylinder' }),
  shape({ id: 'flow.internal-storage', toolId: 'flow-internal-storage', label: 'Internal Storage', category: F, kind: 'shape', geometry: 'internalStorage', description: 'Internal-storage symbol with top and left internal rules.', width: 112, height: 80, defaultText: 'Internal Storage', preview: 'internal-storage' }),
  shape({ id: 'flow.manual-input', toolId: 'flow-manual-input', label: 'Manual Input', category: F, kind: 'shape', geometry: 'manualInput', description: 'Flowchart manual-input symbol with a slanted top edge.', width: 120, height: 76, defaultText: 'Manual Input', preview: 'manual-input' }),
  shape({ id: 'flow.manual-operation', toolId: 'flow-manual-operation', label: 'Manual Operation', category: F, kind: 'shape', geometry: 'manualOperation', description: 'Flowchart manual-operation trapezoid.', width: 120, height: 76, defaultText: 'Manual Operation', preview: 'manual-operation' }),
  shape({ id: 'flow.preparation', toolId: 'flow-preparation', label: 'Preparation', category: F, kind: 'shape', geometry: 'preparation', description: 'Flowchart preparation hexagon.', width: 120, height: 76, defaultText: 'Preparation', preview: 'preparation' }),
  shape({ id: 'flow.display', toolId: 'flow-display', label: 'Display', category: F, kind: 'shape', geometry: 'display', description: 'Flowchart display screen with a curved viewing edge.', width: 120, height: 76, defaultText: 'Display', preview: 'display' }),
  shape({ id: 'flow.delay', toolId: 'flow-delay', label: 'Delay', category: F, kind: 'shape', geometry: 'delay', description: 'Flowchart delay shape with a semicircular end.', width: 116, height: 72, defaultText: 'Delay', preview: 'delay' }),
  shape({ id: 'flow.connector', toolId: 'flow-connector', label: 'Connector', category: F, kind: 'shape', geometry: 'ellipse', description: 'Small on-page flowchart connector circle.', width: 54, height: 54, aspectLocked: true, defaultText: '', preview: 'ellipse' }),
  shape({ id: 'flow.off-page-connector', toolId: 'flow-off-page-connector', label: 'Off-page Connector', category: F, kind: 'shape', geometry: 'offPage', description: 'Pentagonal off-page flowchart connector.', width: 94, height: 82, defaultText: '', preview: 'off-page' }),
  shape({ id: 'flow.data', toolId: 'flow-data', label: 'Data', category: F, kind: 'shape', geometry: 'parallelogram', description: 'Legacy alias; use the explicit Input / Output symbol in new diagrams.', width: 120, height: 72, pickerVisible: false, defaultText: 'Data', defaultParams: { skew: 0.18 }, preview: 'parallelogram' }),
  shape({ id: 'flow.direct-access-storage', toolId: 'flow-direct-access-storage', label: 'Direct Access Storage', category: F, kind: 'shape', geometry: 'dataStore', description: 'Direct-access storage drum with curved top and bottom surface rules.', width: 106, height: 88, defaultText: 'Storage', preview: 'data-store' }),
  shape({ id: 'flow.magnetic-disk', toolId: 'flow-magnetic-disk', label: 'Magnetic Disk', category: F, kind: 'shape', geometry: 'magneticDisk', description: 'Flat magnetic-disk platter symbol with concentric surface and storage-track arcs.', width: 104, height: 88, defaultText: 'Disk', preview: 'magnetic-disk' }),
  shape({ id: 'flow.magnetic-tape', toolId: 'flow-magnetic-tape', label: 'Magnetic Tape', category: F, kind: 'shape', geometry: 'magneticTape', description: 'Flowchart magnetic-tape reel symbol.', width: 114, height: 88, defaultText: 'Tape', preview: 'magnetic-tape' }),
  shape({ id: 'flow.summing-junction', toolId: 'flow-summing-junction', label: 'Summing Junction', category: F, kind: 'shape', geometry: 'summingJunction', description: 'Circular summing junction with a plus marker.', width: 64, height: 64, aspectLocked: true, defaultText: '', preview: 'summing-junction' }),
  shape({ id: 'flow.collate', toolId: 'flow-collate', label: 'Collate', category: F, kind: 'shape', geometry: 'collate', description: 'Flowchart collation symbol.', width: 112, height: 88, defaultText: 'Collate', preview: 'collate' }),
  shape({ id: 'flow.sort', toolId: 'flow-sort', label: 'Sort', category: F, kind: 'shape', geometry: 'sort', description: 'Flowchart sort symbol with a diamond and separator.', width: 112, height: 88, defaultText: 'Sort', preview: 'sort' }),
  shape({ id: 'flow.extract', toolId: 'flow-extract', label: 'Extract', category: F, kind: 'shape', geometry: 'extract', description: 'Flowchart extract operation symbol.', width: 112, height: 82, defaultText: 'Extract', preview: 'extract' }),
  shape({ id: 'flow.merge', toolId: 'flow-merge', label: 'Merge', category: F, kind: 'shape', geometry: 'merge', description: 'Flowchart merge operation symbol.', width: 112, height: 82, defaultText: 'Merge', preview: 'merge' }),

  // UML use case, classifiers, components, sequence, state and activity symbols.
  shape({ id: 'uml.actor', toolId: 'uml-actor', label: 'Actor', category: UC, kind: 'shape', geometry: 'actor', description: 'UML use-case actor drawn as a parametric stick figure.', searchAliases: ['UML Actor', 'Use Case Actor', 'basic.actor', 'Basic Actor'], width: 74, height: 104, resizePolicy: { mode: 'aspect', aspectRatio: 74 / 104 }, preview: 'actor' }),
  shape({ id: 'uml.use-case', toolId: 'uml-use-case', label: 'Use Case', category: UC, kind: 'shape', geometry: 'useCase', description: 'UML use case ellipse.', width: 128, height: 72, defaultText: 'Use Case', preview: 'ellipse' }),
  shape({ id: 'uml.system-boundary', toolId: 'uml-system-boundary', label: 'System Boundary', category: UC, kind: 'shape', geometry: 'umlBoundary', description: 'System boundary with title and container outline.', width: 180, height: 130, defaultText: 'System', preview: 'system-boundary' }),
  shape({ id: 'uml.package', toolId: 'uml-package', label: 'Package', category: C, kind: 'shape', geometry: 'package', description: 'UML package with a folder tab.', width: 132, height: 92, defaultText: 'Package', preview: 'package' }),
  shape({ id: 'uml.note', toolId: 'uml-note', label: 'Note', category: C, kind: 'shape', geometry: 'note', description: 'UML note with a folded corner.', width: 112, height: 82, defaultText: 'Note', preview: 'note' }),
  shape({ id: 'uml.class', toolId: 'uml-class', label: 'Class', category: C, kind: 'shape', geometry: 'table', description: 'Editable class classifier with name, attributes and methods compartments.', width: 166, height: 126, defaultText: 'Class', defaultParams: { compartments: 3, stereotype: '' }, defaultData: { classifier: { compartments: [{ id: 'attributes', label: 'Attributes', items: ['+ attribute'] }, { id: 'operations', label: 'Operations', items: ['+ method()'] }] } }, preview: 'class' }),
  shape({ id: 'uml.abstract-class', toolId: 'uml-abstract-class', label: 'Abstract Class', category: C, kind: 'shape', geometry: 'table', description: 'Classifier with abstract-class semantics and compartment layout.', width: 166, height: 126, defaultText: 'Abstract Class', defaultParams: { compartments: 3, stereotype: '«abstract»', italicName: true }, defaultData: { classifier: { compartments: [{ id: 'attributes', label: 'Attributes', items: ['+ attribute'] }, { id: 'operations', label: 'Operations', items: ['+ method()'] }] } }, preview: 'class' }),
  shape({ id: 'uml.interface', toolId: 'uml-interface', label: 'Interface', category: C, kind: 'shape', geometry: 'table', description: 'Interface classifier with editable operations compartment.', width: 160, height: 106, defaultText: 'Interface', defaultParams: { compartments: 2, stereotype: '«interface»' }, defaultData: { classifier: { compartments: [{ id: 'operations', label: 'Operations', items: ['+ operation()'] }] } }, preview: 'class' }),
  shape({ id: 'uml.enumeration', toolId: 'uml-enumeration', label: 'Enumeration', category: C, kind: 'shape', geometry: 'table', description: 'Enumeration classifier with values compartment.', width: 154, height: 106, defaultText: 'Enumeration', defaultParams: { compartments: 2, stereotype: '«enumeration»' }, defaultData: { classifier: { compartments: [{ id: 'values', label: 'Values', items: ['VALUE_A', 'VALUE_B'] }] } }, preview: 'class' }),
  shape({ id: 'uml.object', toolId: 'uml-object', label: 'Object', category: C, kind: 'shape', geometry: 'table', description: 'UML object instance with a name and values compartment.', width: 150, height: 100, defaultText: 'objectName: Class', defaultParams: { compartments: 2, underlineName: true }, defaultData: { classifier: { compartments: [{ id: 'values', label: 'Values', items: ['attribute = value'] }] } }, preview: 'class' }),
  shape({ id: 'uml-association', toolId: 'uml-association', label: 'Association', category: UC, pickerCategories: [C], kind: 'connector', geometry: 'rect', description: 'UML association connector, shared by Use Case and Class diagrams.', width: 120, height: 0, connector: { endMarker: 'none' }, preview: 'line' }),
  shape({ id: 'uml-directed-association', toolId: 'uml-directed-association', label: 'Directed Association', category: UC, pickerCategories: [C], kind: 'connector', geometry: 'rect', description: 'Navigable UML association shared by Use Case and Class diagrams.', width: 120, height: 0, connector: { endMarker: 'arrow' }, preview: 'arrow' }),
  shape({ id: 'uml.include', toolId: 'uml-include', label: 'Include', category: UC, kind: 'connector', geometry: 'rect', description: 'Dashed use-case include dependency pointing from the including use case to the included use case.', width: 120, height: 0, defaultLabel: '«include»', connector: { lineStyle: 'dashed', endMarker: 'openArrow' }, preview: 'dashed' }),
  shape({ id: 'uml.extend', toolId: 'uml-extend', label: 'Extend', category: UC, kind: 'connector', geometry: 'rect', description: 'Dashed use-case extend dependency pointing from the extending use case to the extended base use case.', width: 120, height: 0, defaultLabel: '«extend»', connector: { lineStyle: 'dashed', endMarker: 'openArrow' }, preview: 'dashed' }),
  shape({ id: 'uml-aggregation', toolId: 'uml-aggregation', label: 'Aggregation', category: C, kind: 'connector', geometry: 'rect', description: 'Association with a hollow-diamond aggregate endpoint.', width: 120, height: 0, connector: { startMarker: 'diamond' }, preview: 'aggregation' }),
  shape({ id: 'uml-composition', toolId: 'uml-composition', label: 'Composition', category: C, kind: 'connector', geometry: 'rect', description: 'Association with a filled-diamond composition endpoint.', width: 120, height: 0, connector: { startMarker: 'filledDiamond' }, preview: 'composition' }),
  shape({ id: 'uml-generalization', toolId: 'uml-generalization', label: 'Generalization / Inheritance', category: C, pickerCategories: [UC], kind: 'connector', geometry: 'rect', description: 'UML generalization with a hollow triangle endpoint.', width: 120, height: 0, connector: { endMarker: 'hollowTriangle' }, preview: 'generalization' }),
  shape({ id: 'uml-dependency', toolId: 'uml-dependency', label: 'Dependency', category: C, kind: 'connector', geometry: 'rect', description: 'Dashed UML dependency with an open arrowhead.', width: 120, height: 0, connector: { lineStyle: 'dashed', endMarker: 'openArrow' }, preview: 'dashed' }),
  shape({ id: 'uml-realization', toolId: 'uml-realization', label: 'Realization', category: C, kind: 'connector', geometry: 'rect', description: 'Dashed realization connector with a hollow triangle endpoint.', width: 120, height: 0, connector: { lineStyle: 'dashed', endMarker: 'hollowTriangle' }, preview: 'generalization' }),
  shape({ id: 'uml-usage', toolId: 'uml-usage', label: 'Usage', category: C, kind: 'connector', geometry: 'rect', description: 'Dashed UML usage dependency marked with the «use» stereotype.', width: 120, height: 0, defaultLabel: '«use»', connector: { lineStyle: 'dashed', endMarker: 'openArrow' }, preview: 'dashed' }),
  shape({ id: 'uml.component', toolId: 'uml-component', label: 'Component', category: C, kind: 'shape', geometry: 'frame', description: 'UML component with component glyph and name.', width: 136, height: 92, defaultText: 'Component', defaultParams: { componentGlyph: true }, preview: 'component' }),
  shape({ id: 'uml.provided-interface', toolId: 'uml-provided-interface', label: 'Provided Interface', category: C, kind: 'shape', geometry: 'umlProvidedInterface', description: 'Provided interface shown as a lollipop circle and attachment stem.', width: 64, height: 48, defaultParams: { lollipop: 'provided' }, preview: 'provided-interface' }),
  shape({ id: 'uml.required-interface', toolId: 'uml-required-interface', label: 'Required Interface', category: C, kind: 'shape', geometry: 'umlRequiredInterface', description: 'Required interface shown as an open socket attached to its component edge.', width: 64, height: 48, defaultParams: { lollipop: 'required' }, preview: 'required-interface' }),
  shape({ id: 'uml-assembly-connector', toolId: 'uml-assembly-connector', label: 'Assembly Connector', category: C, kind: 'connector', geometry: 'rect', description: 'Connector used to join provided and required interfaces.', width: 80, height: 0, connector: { endMarker: 'none' }, preview: 'line' }),
  shape({ id: 'uml.module', toolId: 'uml-module', label: 'Module', category: C, kind: 'shape', geometry: 'package', description: 'UML module/package container.', width: 132, height: 92, defaultText: 'Module', defaultParams: { stereotype: '«module»' }, preview: 'package' }),
  shape({ id: 'uml.lifeline', toolId: 'uml-lifeline', label: 'Lifeline', category: S, kind: 'shape', geometry: 'umlLifeline', description: 'Sequence participant header with a solid box and independently dashed vertical lifeline.', width: 118, height: 220, defaultText: 'Lifeline', preview: 'lifeline' }),
  shape({ id: 'uml.sequence-actor', toolId: 'uml-sequence-actor', label: 'Actor / Participant', category: S, kind: 'shape', geometry: 'umlActorParticipant', description: 'Actor participant above a dashed sequence lifeline, with an editable name band.', width: 92, height: 210, defaultText: 'Actor', preview: 'actor-lifeline' }),
  shape({ id: 'uml.sequence-message', toolId: 'uml-sequence-message', label: 'Message', category: S, pickerLabels: { [S]: 'Sequence Message' }, kind: 'connector', geometry: 'rect', description: 'Solid UML message arrow between sequence participants.', searchAliases: ['Sequence Message', 'Message Arrow', 'Call Message'], width: 120, height: 0, connector: { endMarker: 'arrow' }, preview: 'arrow' }),
  shape({ id: 'uml.create-message', toolId: 'uml-create-message', label: 'Create Message', category: S, kind: 'connector', geometry: 'rect', description: 'Directed UML creation message from a sequence participant to a newly starting lifeline.', width: 120, height: 0, defaultLabel: 'create', connector: { endMarker: 'arrow' }, preview: 'arrow' }),
  shape({ id: 'uml.return-message', toolId: 'uml-return-message', label: 'Return Message', category: S, kind: 'connector', geometry: 'rect', description: 'Dashed UML return message with an open arrowhead.', width: 120, height: 0, defaultLabel: 'return', connector: { lineStyle: 'dashed', endMarker: 'openArrow' }, preview: 'dashed' }),
  shape({ id: 'uml.activation', toolId: 'uml-activation', label: 'Activation', category: S, kind: 'shape', geometry: 'umlActivation', description: 'Narrow UML activation bar.', width: 24, height: 90, preview: 'activation' }),
  shape({ id: 'uml.boundary', toolId: 'uml-boundary', label: 'Boundary', category: S, kind: 'shape', geometry: 'umlRole', description: 'Sequence boundary object with boundary stereotype and ECB symbol.', width: 90, height: 82, defaultText: 'Boundary', defaultParams: { stereotype: '«boundary»' }, preview: 'role', previewGlyph: 'B' }),
  shape({ id: 'uml.control', toolId: 'uml-control', label: 'Control', category: S, kind: 'shape', geometry: 'umlRole', description: 'Sequence control object with control stereotype and ECB symbol.', width: 90, height: 82, defaultText: 'Control', defaultParams: { stereotype: '«control»' }, preview: 'role', previewGlyph: 'C' }),
  shape({ id: 'uml.entity', toolId: 'uml-entity', label: 'Entity', category: S, kind: 'shape', geometry: 'umlRole', description: 'Sequence entity object with entity stereotype and ECB symbol.', width: 90, height: 82, defaultText: 'Entity', defaultParams: { stereotype: '«entity»' }, preview: 'role', previewGlyph: 'E' }),
  shape({ id: 'uml.destroy', toolId: 'uml-destroy', label: 'Destroy', category: S, kind: 'shape', geometry: 'umlDestroy', description: 'Sequence diagram destruction cross.', width: 26, height: 26, aspectLocked: true, preview: 'destroy' }),
  shape({ id: 'uml.frame', toolId: 'uml-frame', label: 'Frame', category: S, kind: 'shape', geometry: 'frame', description: 'Sequence/activity diagram frame with an operator tab.', width: 160, height: 120, defaultText: 'sd Frame', defaultParams: { title: 'sd' }, preview: 'frame' }),
  shape({ id: 'uml.state', toolId: 'uml-state', label: 'State', category: ST, kind: 'shape', geometry: 'umlState', description: 'Rounded UML state with optional entry/do/exit text.', width: 124, height: 78, defaultText: 'State', defaultParams: { cornerRadiusRatio: 0.16 }, preview: 'roundedRect' }),
  shape({ id: 'uml.composite-state', toolId: 'uml-composite-state', label: 'Composite State', category: ST, kind: 'shape', geometry: 'umlCompositeState', description: 'Composite state with a dedicated name compartment and nested-state area.', width: 152, height: 108, defaultText: 'Composite State', preview: 'composite-state' }),
  shape({ id: 'uml.initial-state', toolId: 'uml-initial-state', label: 'Initial State', category: ST, kind: 'shape', geometry: 'umlInitialState', description: 'Black-filled UML initial-state pseudostate, also used as an activity initial node; user fill remains transparent.', width: 28, height: 28, aspectLocked: true, pickerCategories: [ACT], pickerLabels: { [ACT]: 'Initial Node' }, preview: 'initial-state' }),
  shape({ id: 'uml.final-state', toolId: 'uml-final-state', label: 'Final State', category: ST, kind: 'shape', geometry: 'umlFinalState', description: 'UML final-state bullseye with a filled center and hollow ring, also used as an activity final node.', width: 34, height: 34, aspectLocked: true, pickerCategories: [ACT], pickerLabels: { [ACT]: 'Final Node' }, preview: 'final-state' }),
  shape({ id: 'uml.choice-junction', toolId: 'uml-choice-junction', label: 'Choice / Junction', category: ST, kind: 'shape', geometry: 'umlPseudoChoice', description: 'State-machine choice or junction pseudostate; distinct from a generic diamond by its UML transition role.', width: 54, height: 54, aspectLocked: true, defaultParams: { pseudostate: 'choice-or-junction' }, preview: 'diamond' }),
  shape({ id: 'uml.shallow-history', toolId: 'uml-shallow-history', label: 'Shallow History', category: ST, kind: 'shape', geometry: 'umlHistory', description: 'Shallow-history pseudostate marked H.', width: 38, height: 38, aspectLocked: true, defaultText: 'H', defaultParams: { history: 'shallow' }, preview: 'history' }),
  shape({ id: 'uml.deep-history', toolId: 'uml-deep-history', label: 'Deep History', category: ST, kind: 'shape', geometry: 'umlHistory', description: 'Deep-history pseudostate marked H*.', width: 38, height: 38, aspectLocked: true, defaultText: 'H*', defaultParams: { history: 'deep' }, preview: 'deep-history' }),
  shape({ id: 'uml.entry-point', toolId: 'uml-entry-point', label: 'Entry Point', category: ST, kind: 'shape', geometry: 'umlEntryPoint', description: 'Entry point placed on the edge of a composite state.', width: 28, height: 28, aspectLocked: true, preview: 'entry-point' }),
  shape({ id: 'uml.exit-point', toolId: 'uml-exit-point', label: 'Exit Point', category: ST, kind: 'shape', geometry: 'umlExitPoint', description: 'Exit point marked by a cross inside a circle.', width: 28, height: 28, aspectLocked: true, preview: 'exit-point' }),
  shape({ id: 'uml.state-transition', toolId: 'uml-state-transition', label: 'Transition', category: ST, kind: 'connector', geometry: 'rect', description: 'Directed UML state-machine transition.', width: 120, height: 0, connector: { endMarker: 'arrow' }, preview: 'arrow' }),
  shape({ id: 'uml.decision', toolId: 'uml-decision', label: 'Decision / Merge', category: ACT, kind: 'shape', geometry: 'diamond', description: 'UML activity decision or merge node; direction distinguishes branching from convergence.', width: 86, height: 72, preview: 'diamond' }),
  shape({ id: 'uml.fork', toolId: 'uml-fork', label: 'Fork / Join', category: ACT, pickerCategories: [ST], kind: 'shape', geometry: 'umlFork', description: 'UML activity/state-machine fork or join bar with semantic filled body.', width: 132, height: 18, preview: 'fork' }),
  shape({ id: 'uml.activity', toolId: 'uml-activity', label: 'Activity', category: ACT, kind: 'shape', geometry: 'frame', description: 'Named UML activity frame with the act operator.', width: 160, height: 120, defaultText: 'act Activity', defaultParams: { title: 'act' }, preview: 'frame' }),
  shape({ id: 'uml.action', toolId: 'uml-action', label: 'Action', category: ACT, kind: 'shape', geometry: 'umlActivity', description: 'Rounded UML action node.', width: 132, height: 72, defaultText: 'Action', defaultParams: { cornerRadiusRatio: 0.17 }, preview: 'roundedRect' }),
  shape({ id: 'uml.object-node', toolId: 'uml-object-node', label: 'Object Node', category: ACT, kind: 'shape', geometry: 'rect', description: 'Object token node with editable object or type label.', width: 112, height: 64, defaultText: 'object : Type', preview: 'object-node', previewGlyph: 'obj' }),
  shape({ id: 'uml.activity-partition', toolId: 'uml-activity-partition', label: 'Activity Partition', category: ACT, kind: 'shape', geometry: 'activityPartition', description: 'Horizontal-header activity partition/swimlane with independent content area.', width: 220, height: 140, defaultText: 'Partition', preview: 'activity-partition' }),
  shape({ id: 'uml.activity-flow', toolId: 'uml-activity-flow', label: 'Control Flow', category: ACT, kind: 'connector', geometry: 'rect', description: 'Directed UML activity control-flow edge.', width: 120, height: 0, connector: { endMarker: 'arrow' }, preview: 'arrow' }),

  // ERD / Database. Cardinality is endpoint metadata on connectors rather than extra objects.
  shape({ id: 'erd.entity', toolId: 'erd-entity', label: 'Entity', category: E, kind: 'shape', geometry: 'rect', description: 'Entity rectangle with editable name.', width: 128, height: 76, defaultText: 'Entity', preview: 'rect' }),
  shape({ id: 'erd.weak-entity', toolId: 'erd-weak-entity', label: 'Weak Entity', category: E, kind: 'shape', geometry: 'rect', description: 'Weak entity with a double outline.', width: 128, height: 76, defaultText: 'Weak Entity', defaultParams: { doubleBorder: true }, preview: 'weak-entity' }),
  shape({ id: 'erd.associative-entity', toolId: 'erd-associative-entity', label: 'Associative Entity', category: E, kind: 'shape', geometry: 'diamond', description: 'Associative entity with a composite entity/relationship outline.', width: 128, height: 96, defaultText: 'Associative Entity', defaultParams: { innerDiamond: true }, preview: 'associative-entity' }),
  shape({ id: 'erd.relationship', toolId: 'erd-relationship', label: 'Relationship', category: E, kind: 'shape', geometry: 'diamond', description: 'ER relationship diamond.', width: 106, height: 76, defaultText: 'Relationship', preview: 'diamond' }),
  shape({ id: 'erd.identifying-relationship', toolId: 'erd-identifying-relationship', label: 'Identifying Relationship', category: E, kind: 'shape', geometry: 'diamond', description: 'Identifying relationship with a double diamond outline.', width: 110, height: 82, defaultText: 'Identifies', defaultParams: { doubleBorder: true }, preview: 'double-diamond' }),
  shape({ id: 'erd.attribute', toolId: 'erd-attribute', label: 'Attribute', category: E, kind: 'shape', geometry: 'ellipse', description: 'ER attribute ellipse.', width: 110, height: 58, defaultText: 'Attribute', preview: 'ellipse' }),
  shape({ id: 'erd.primary-key-attribute', toolId: 'erd-primary-key-attribute', label: 'Primary Key Attribute', category: E, kind: 'shape', geometry: 'ellipse', description: 'Attribute with an underlined primary-key label.', width: 120, height: 60, defaultText: 'id', defaultParams: { key: 'primary', underline: true }, preview: 'primary-key' }),
  shape({ id: 'erd.foreign-key-attribute', toolId: 'erd-foreign-key-attribute', label: 'Foreign Key Attribute', category: E, kind: 'shape', geometry: 'ellipse', description: 'Attribute with a visible FK marker and foreign-key metadata.', width: 120, height: 60, defaultText: 'foreign_id', defaultParams: { key: 'foreign' }, preview: 'foreign-key', previewGlyph: 'FK' }),
  shape({ id: 'erd.multivalued-attribute', toolId: 'erd-multivalued-attribute', label: 'Multivalued Attribute', category: E, kind: 'shape', geometry: 'ellipse', description: 'Multivalued ER attribute with a double ellipse.', width: 120, height: 64, defaultText: 'Values', defaultParams: { doubleBorder: true }, preview: 'double-ellipse' }),
  shape({ id: 'erd.derived-attribute', toolId: 'erd-derived-attribute', label: 'Derived Attribute', category: E, kind: 'shape', geometry: 'ellipse', description: 'Derived ER attribute with a dashed outline.', width: 116, height: 60, defaultText: 'Derived', defaultParams: { lineStyle: 'dashed' }, preview: 'dashed-ellipse' }),
  shape({ id: 'erd.database', toolId: 'erd-database', label: 'Database', category: E, kind: 'shape', geometry: 'cylinder', description: 'Database cylinder.', width: 108, height: 94, defaultText: 'Database', preview: 'cylinder' }),
  shape({ id: 'erd.table', toolId: 'erd-table', label: 'Table', category: E, kind: 'shape', geometry: 'table', description: 'Legacy generic table alias; the richer ER Table is the single visible table tool.', width: 160, height: 128, pickerVisible: false, defaultText: 'Table', defaultParams: { compartments: 2, rowCount: 3 }, defaultData: { table: { columns: [{ id: 'id', name: 'id', type: 'integer', key: 'primary' }, { id: 'name', name: 'name', type: 'text', key: 'none' }] } }, preview: 'table' }),
  shape({ id: 'erd.er-table', toolId: 'erd-er-table', label: 'ER Table', category: E, kind: 'shape', geometry: 'table', description: 'Structured editable ER table with persistent column and key metadata.', searchAliases: ['ERD Table', 'Database Table', 'erd.table'], width: 170, height: 140, defaultText: 'Entity', defaultParams: { compartments: 2, rowCount: 3 }, defaultData: { table: { columns: [{ id: 'id', name: 'id', type: 'integer', key: 'primary' }, { id: 'parent_id', name: 'parent_id', type: 'integer', key: 'foreign' }] } }, preview: 'table' }),
  shape({ id: 'erd.column', toolId: 'erd-column', label: 'Column', category: E, kind: 'shape', geometry: 'column', description: 'Database column row with editable name/type.', width: 150, height: 34, defaultText: 'column : type', defaultData: { column: { name: 'column', type: 'type', key: 'none' } }, preview: 'column' }),
  shape({ id: 'erd.key-marker', toolId: 'erd-key-marker', label: 'Key / Identifier Marker', category: E, kind: 'shape', geometry: 'keyMarker', description: 'Standalone key glyph; key-role labels are rendered on structured table columns and attributes.', width: 28, height: 28, aspectLocked: true, preview: 'key' }),
  shape({ id: 'erd.relationship-connector', toolId: 'erd-relationship-connector', label: 'ER Relationship Connector', category: E, kind: 'connector', geometry: 'rect', description: 'Relationship connector with editable crow-foot cardinality at both ends.', width: 120, height: 0, connector: { startMarker: 'crowFoot', endMarker: 'crowFoot', sourceCardinality: 'many', targetCardinality: 'many' }, preview: 'crow-foot' }),

  // Core BPMN 2.0 notation; extensible by adding semantic definitions using these primitives.
  shape({ id: 'bpmn.sequence-flow', toolId: 'bpmn-sequence-flow', label: 'BPMN Sequence Flow', category: ACT, kind: 'connector', geometry: 'rect', description: 'BPMN sequence flow with a solid arrowhead.', width: 120, height: 0, connector: { endMarker: 'arrow' }, preview: 'arrow' }),
  shape({ id: 'bpmn.message-flow', toolId: 'bpmn-message-flow', label: 'BPMN Message Flow', category: ACT, kind: 'connector', geometry: 'rect', description: 'BPMN message flow with dashed line, open arrow and start circle.', width: 120, height: 0, connector: { lineStyle: 'dashed', startMarker: 'circle', endMarker: 'openArrow' }, preview: 'dashed' }),
  shape({ id: 'bpmn.association', toolId: 'bpmn-association', label: 'BPMN Association', category: ACT, kind: 'connector', geometry: 'rect', description: 'BPMN dotted association connector.', width: 120, height: 0, connector: { lineStyle: 'dotted', endMarker: 'none' }, preview: 'dashed' }),
  shape({ id: 'bpmn.data-association', toolId: 'bpmn-data-association', label: 'BPMN Data Association', category: ACT, kind: 'connector', geometry: 'rect', description: 'BPMN dotted data association with an open arrowhead.', width: 120, height: 0, connector: { lineStyle: 'dotted', endMarker: 'openArrow' }, preview: 'open-arrow' }),
  shape({ id: 'bpmn.start-event', toolId: 'bpmn-start-event', label: 'BPMN Start Event', category: ACT, kind: 'shape', geometry: 'bpmnEvent', description: 'BPMN start event with a single thin circular boundary.', width: 44, height: 44, aspectLocked: true, defaultParams: { eventKind: 'start', marker: 'none' }, preview: 'initial-state' }),
  shape({ id: 'bpmn.intermediate-event', toolId: 'bpmn-intermediate-event', label: 'BPMN Intermediate Event', category: ACT, kind: 'shape', geometry: 'bpmnEvent', description: 'BPMN intermediate event with a double circular boundary.', width: 48, height: 48, aspectLocked: true, defaultParams: { eventKind: 'intermediate', marker: 'none' }, preview: 'bpmn-intermediate' }),
  shape({ id: 'bpmn.end-event', toolId: 'bpmn-end-event', label: 'BPMN End Event', category: ACT, kind: 'shape', geometry: 'bpmnEvent', description: 'BPMN end event with a thick circular boundary.', width: 44, height: 44, aspectLocked: true, defaultParams: { eventKind: 'end', marker: 'none' }, preview: 'bpmn-end' }),
  shape({ id: 'bpmn.message-event', toolId: 'bpmn-message-event', label: 'BPMN Message Event', category: ACT, kind: 'shape', geometry: 'bpmnEvent', description: 'BPMN message event with envelope marker.', width: 48, height: 48, aspectLocked: true, defaultParams: { eventKind: 'intermediate', marker: 'message' }, preview: 'bpmn-message' }),
  shape({ id: 'bpmn.timer-event', toolId: 'bpmn-timer-event', label: 'BPMN Timer Event', category: ACT, kind: 'shape', geometry: 'bpmnEvent', description: 'BPMN timer event with clock marker.', width: 48, height: 48, aspectLocked: true, defaultParams: { eventKind: 'intermediate', marker: 'timer' }, preview: 'bpmn-timer' }),
  shape({ id: 'bpmn.error-event', toolId: 'bpmn-error-event', label: 'BPMN Error Event', category: ACT, kind: 'shape', geometry: 'bpmnEvent', description: 'BPMN error event with lightning marker.', width: 48, height: 48, aspectLocked: true, defaultParams: { eventKind: 'end', marker: 'error' }, preview: 'bpmn-error' }),
  shape({ id: 'bpmn.signal-event', toolId: 'bpmn-signal-event', label: 'BPMN Signal Event', category: ACT, kind: 'shape', geometry: 'bpmnEvent', description: 'BPMN signal event with signal marker.', width: 48, height: 48, aspectLocked: true, defaultParams: { eventKind: 'intermediate', marker: 'signal' }, preview: 'bpmn-signal' }),
  shape({ id: 'bpmn-user-task', toolId: 'bpmn-user-task', label: 'BPMN User Task', category: ACT, kind: 'shape', geometry: 'bpmnTask', description: 'Rounded BPMN user task with person marker.', width: 146, height: 82, defaultText: 'User Task', defaultParams: { taskMarker: 'user' }, preview: 'bpmn-task' }),
  shape({ id: 'bpmn-manual-task', toolId: 'bpmn-manual-task', label: 'BPMN Manual Task', category: ACT, kind: 'shape', geometry: 'bpmnTask', description: 'Rounded BPMN manual task with hand marker.', width: 146, height: 82, defaultText: 'Manual Task', defaultParams: { taskMarker: 'manual' }, preview: 'bpmn-task' }),
  shape({ id: 'bpmn-service-task', toolId: 'bpmn-service-task', label: 'BPMN Service Task', category: ACT, kind: 'shape', geometry: 'bpmnTask', description: 'Rounded BPMN service task with gear marker.', width: 146, height: 82, defaultText: 'Service Task', defaultParams: { taskMarker: 'service' }, preview: 'bpmn-task' }),
  shape({ id: 'bpmn-script-task', toolId: 'bpmn-script-task', label: 'BPMN Script Task', category: ACT, kind: 'shape', geometry: 'bpmnTask', description: 'Rounded BPMN script task with script marker.', width: 146, height: 82, defaultText: 'Script Task', defaultParams: { taskMarker: 'script' }, preview: 'bpmn-task' }),
  shape({ id: 'bpmn-business-rule-task', toolId: 'bpmn-business-rule-task', label: 'BPMN Business Rule Task', category: ACT, kind: 'shape', geometry: 'bpmnTask', description: 'Rounded BPMN business-rule task with rule marker.', width: 146, height: 82, defaultText: 'Business Rule Task', defaultParams: { taskMarker: 'rule' }, preview: 'bpmn-task' }),
  shape({ id: 'bpmn-receive-task', toolId: 'bpmn-receive-task', label: 'BPMN Receive Task', category: ACT, kind: 'shape', geometry: 'bpmnTask', description: 'Rounded BPMN receive task with envelope marker.', width: 146, height: 82, defaultText: 'Receive Task', defaultParams: { taskMarker: 'receive' }, preview: 'bpmn-task' }),
  shape({ id: 'bpmn-send-task', toolId: 'bpmn-send-task', label: 'BPMN Send Task', category: ACT, kind: 'shape', geometry: 'bpmnTask', description: 'Rounded BPMN send task with envelope marker.', width: 146, height: 82, defaultText: 'Send Task', defaultParams: { taskMarker: 'send' }, preview: 'bpmn-task' }),
  shape({ id: 'bpmn-call-activity', toolId: 'bpmn-call-activity', label: 'BPMN Call Activity', category: ACT, kind: 'shape', geometry: 'bpmnTask', description: 'BPMN call activity with a bold outer border.', width: 146, height: 82, defaultText: 'Call Activity', defaultParams: { callActivity: true }, preview: 'bpmn-call' }),
  shape({ id: 'bpmn-subprocess', toolId: 'bpmn-subprocess', label: 'BPMN Subprocess', category: ACT, kind: 'shape', geometry: 'bpmnTask', description: 'Expandable BPMN subprocess with plus marker.', width: 146, height: 82, defaultText: 'Subprocess', defaultParams: { subprocess: true }, preview: 'bpmn-subprocess' }),
  shape({ id: 'bpmn-exclusive-gateway', toolId: 'bpmn-exclusive-gateway', label: 'BPMN Exclusive Gateway', category: ACT, kind: 'shape', geometry: 'bpmnGateway', description: 'BPMN exclusive gateway with an X marker.', width: 66, height: 66, aspectLocked: true, defaultParams: { gatewayMarker: 'x' }, preview: 'gateway-x' }),
  shape({ id: 'bpmn-inclusive-gateway', toolId: 'bpmn-inclusive-gateway', label: 'BPMN Inclusive Gateway', category: ACT, kind: 'shape', geometry: 'bpmnGateway', description: 'BPMN inclusive gateway with a circle marker.', width: 66, height: 66, aspectLocked: true, defaultParams: { gatewayMarker: 'circle' }, preview: 'gateway-circle' }),
  shape({ id: 'bpmn-parallel-gateway', toolId: 'bpmn-parallel-gateway', label: 'BPMN Parallel Gateway', category: ACT, kind: 'shape', geometry: 'bpmnGateway', description: 'BPMN parallel gateway with a plus marker.', width: 66, height: 66, aspectLocked: true, defaultParams: { gatewayMarker: 'plus' }, preview: 'gateway-plus' }),
  shape({ id: 'bpmn-event-gateway', toolId: 'bpmn-event-gateway', label: 'BPMN Event-Based Gateway', category: ACT, kind: 'shape', geometry: 'bpmnGateway', description: 'BPMN event gateway with pentagon/star marker.', width: 66, height: 66, aspectLocked: true, defaultParams: { gatewayMarker: 'event' }, preview: 'gateway-event' }),
  shape({ id: 'bpmn-data-object', toolId: 'bpmn-data-object', label: 'BPMN Data Object', category: ACT, kind: 'shape', geometry: 'dataObject', description: 'BPMN data object with folded corner.', width: 76, height: 94, defaultText: 'Data', preview: 'data-object' }),
  shape({ id: 'bpmn-data-store', toolId: 'bpmn-data-store', label: 'BPMN Data Store', category: ACT, kind: 'shape', geometry: 'dataStore', description: 'BPMN data store with cylindrical boundary.', width: 100, height: 94, defaultText: 'Store', preview: 'cylinder' }),
  shape({ id: 'bpmn-message', toolId: 'bpmn-message', label: 'BPMN Message', category: ACT, kind: 'shape', geometry: 'dataObject', description: 'BPMN message envelope object.', width: 84, height: 54, defaultText: 'Message', defaultParams: { messageEnvelope: true }, preview: 'bpmn-message' }),
  shape({ id: 'bpmn-pool', toolId: 'bpmn-pool', label: 'BPMN Pool', category: ACT, kind: 'shape', geometry: 'pool', description: 'BPMN pool with a participant label band.', width: 260, height: 150, defaultText: 'Participant', preview: 'pool' }),
  shape({ id: 'bpmn-lane', toolId: 'bpmn-lane', label: 'BPMN Lane', category: ACT, kind: 'shape', geometry: 'lane', description: 'BPMN lane with a vertical name band.', width: 260, height: 132, defaultText: 'Lane', preview: 'lane' }),
  shape({ id: 'bpmn-group', toolId: 'bpmn-group', label: 'BPMN Group', category: ACT, kind: 'shape', geometry: 'group', description: 'Dashed BPMN group outline.', width: 190, height: 122, defaultText: 'Group', defaultParams: { lineStyle: 'dashed' }, preview: 'group' }),
  shape({ id: 'bpmn-annotation', toolId: 'bpmn-annotation', label: 'BPMN Annotation', category: ACT, kind: 'shape', geometry: 'annotation', description: 'BPMN text annotation with bracket and text area.', width: 150, height: 92, defaultText: 'Annotation', preview: 'annotation' }),
] as const satisfies readonly ShapeDefinition[];

export type ShapeDefinitionUnion = typeof SHAPE_DEFINITIONS[number];
export type RegisteredShapeToolId = ShapeDefinitionUnion['toolId'];
export type RegisteredBoxShapeToolId = Extract<ShapeDefinitionUnion, { kind: 'shape' }>['toolId'];
export type RegisteredConnectorToolId = Extract<ShapeDefinitionUnion, { kind: 'connector' }>['toolId'];

const toolMap = new Map<string, ShapeDefinition>();
const idMap = new Map<string, ShapeDefinition>();
const legacyMap = new Map<string, ShapeDefinition>();
for (const definition of SHAPE_DEFINITIONS as readonly ShapeDefinition[]) {
  if (toolMap.has(definition.toolId)) throw new Error(`Duplicate shape tool id: ${definition.toolId}`);
  if (idMap.has(definition.id)) throw new Error(`Duplicate semantic shape id: ${definition.id}`);
  toolMap.set(definition.toolId, definition);
  idMap.set(definition.id, definition);
  if (definition.legacyType) legacyMap.set(definition.legacyType, definition);
}

export function getShapeDefinitionByToolId(toolId: string): ShapeDefinition | undefined {
  const definition = toolMap.get(toolId);
  return definition?.category === 'Flowchart' ? undefined : definition;
}

/** Resolve only tools that are currently discoverable to new users; hidden definitions remain
 * available through getShapeDefinitionByToolId for rendering and migrating saved documents. */
export function getVisibleShapeDefinitionByToolId(toolId: string): ShapeDefinition | undefined {
  const definition = getShapeDefinitionByToolId(toolId);
  return definition?.pickerVisible === false ? undefined : definition;
}

export function getShapeDefinition(shapeId: string): ShapeDefinition | undefined {
  return idMap.get(shapeId);
}

export function getShapeDefinitionForLegacyType(type: string): ShapeDefinition | undefined {
  return legacyMap.get(type);
}

/** Resolve explicit resize metadata while preserving legacy aspectLocked square behavior. */
export function getShapeResizePolicy(definition?: Pick<ShapeDefinition, 'resizePolicy' | 'aspectLocked'>): ShapeResizePolicy {
  if (definition?.resizePolicy?.mode === 'aspect') {
    const aspectRatio = definition.resizePolicy.aspectRatio;
    return { mode: 'aspect', aspectRatio: Number.isFinite(aspectRatio) && aspectRatio > 0 ? aspectRatio : 1 };
  }
  if (definition?.resizePolicy?.mode === 'free') return { mode: 'free' };
  if (definition?.aspectLocked) return { mode: 'aspect', aspectRatio: 1 };
  return { mode: 'free' };
}

export function listShapeDefinitions(category?: ShapeDefinition['category']): readonly ShapeDefinition[] {
  return category ? SHAPE_DEFINITIONS.filter(definition => definition.category === category) : SHAPE_DEFINITIONS;
}

export function listShapePickerDefinitions(category?: ShapeDefinition['category']): readonly ShapeDefinition[] {
  return (SHAPE_DEFINITIONS as readonly ShapeDefinition[]).filter(definition => definition.pickerVisible !== false
    && (!category || definition.category === category || definition.pickerCategories?.includes(category)));
}

export function getShapePickerLabel(definition: ShapeDefinition, category: ShapeDefinition['category'] = definition.category): string {
  return definition.pickerLabels?.[category] ?? definition.label;
}

export function isShapeToolId(value: string): value is RegisteredShapeToolId {
  return getVisibleShapeDefinitionByToolId(value) !== undefined;
}

export function defaultShapeParams(definition: ShapeDefinition): Record<string, number | string | boolean> {
  return { ...(definition.defaultParams ?? {}) };
}

export function isShapeDefinitionToolId(value: string): value is ShapeToolId {
  return getVisibleShapeDefinitionByToolId(value) !== undefined;
}
